exports.tapas = [
    {
        photo:'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8YnJ1c2NoZXR0YXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
        label:'Pan Con Tomate',
        ingredients:['bread', 'tomatoes', 'salt', 'olive oil', 'proscutto', 'garlic'],
        stepOne: 'Start by toasting your bread. You can use the toaster or the oven.',
        stepTwo: 'Grate the tomato into a bowl',
        stepThree: 'Add the olive oil and salt to season the grated tomato.',
        stepFour: ' Rub the toasted bread with raw garlic (optional) and then spread the tomato sauce.',
        stepFive: 'Finally, drizzle a bit more extra virgin olive oil and sprinkle some sea salt. Enjoy!',
    },
    {
        photo:'https://images.unsplash.com/photo-1565599837634-889309b9f5d2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjl8fHNwYW5pc2glMjBmb29kfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=700&q=60',
        label:'Croquetas De Jamón Serrano',
        ingredients:['60 grams/4 T unsalted butter', '60 grams olive oil', '1 cup of flour (120 grams)', '1 onion', '1 Liter whole milk at room temperature', 'nutmeg', '250 grams of jamón Serrano', 'flour for breading', '2 eggs', 'bread crumbs, panko' ],
        stepOne: 'Melt the butter and warm the oil in a medium size pan over medium-high heat. Add the onion and sauté for a few minutes until it just starts to brown. Add a pinch of salt and the nutmeg. Add the diced ham and sauté for 30 seconds more.',
        stepTwo: 'Add the flour and stir continually, until the flour turns a light brown color. You must not stop stirring or the flour will burn! When the flour changes color, add the milk little by little, always stirring until you incorporate the entire amount. It should take about 20 minutes to add it all.',
        stepThree: 'Turn off the heat and let the dough cool a bit. Butter the sides of a large bowl or plastic wrap and wrap the croquette dough inside, covered directly with plastic wrap. Refrigerate a minimum of 4 hours but preferably overnight.',
        stepFour: 'To make the ham croquettes shape them into little logs (or use a pastry sleeve if you have one) Next, while heating a pan full of olive oil on the stove, pass the croquettes through the breading process. First, cover them in flour, then in egg, and, finally, in the breadcrumbs.',
        stepFive: 'Fry the ham croquettes in the hot oil and let them cool a few minutes before enjoying!',
    },
    {
        photo:'https://images.unsplash.com/photo-1626011852881-4609127619a8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzB8fHNwYW5pc2glMjBmb29kfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=1600&q=60',
        label:'Croquetas De Mushroom',
        ingredients:['3/4 cup Extra Virgin Spanish Olive Oil', '1 Cup Milk', '1/4 Cup All-Purpuse Flower', '1/2 Cup Breadcrumbs', '7 Button Mushrooms', '1/2 Onion', '1 clove of garlic', '1 egg', 'Parsley', 'Salt'],
        stepOne: 'Finely mince 1 clove of garlic, finely dice 1/2 of an onion and finely dice 7 button mushrooms. Heat a non-stick frying pan with a medium heat and add 1/4 cup extra virgin Spanish olive oil. Once the oil gets hot, season it with sea salt and add the minced garlic to the pan. After about 20 seconds add the diced onions to the pan and mix. After cooking your onions for about 4 minutes add the diced mushrooms to the pan and mix',
        stepTwo: 'About 3 minutes after adding the diced mushrooms, add a generous pinch of freshly chopped parsley and sea salt and mix. Grab a 1/4 cup of all-purpose flour and start adding it to the pan, little by little, while continuing to stir the mixture. Now grab 1 cup of milk and start adding it to the pan, just like the flour, a little at a time while continuing to stir the mixture',
        stepThree: 'Once your mixture becomes into a paste, turn your burner off and transfer the mixture to a bowl and cover with seran wrap. Grab a small bowl and beat 1 egg. Grab 1/2 cup of bread crumbs and add to a seperate bowl. Once your mushroom mixture reaches room temperature remove the seran wrap ',
        stepFour: 'Using a spoon, grab some of the mixture and begin to shape your croquettes, in the size and shape of an egg. Dip the croquettes one by one into the egg bowl and coat well and then into the bowl with the breadcrums and coat well and transfer to a plate',
        stepFive: 'Grab a small non-stick frying pan, heat with a medium heat and add 1/2 cup extra virgin Spanish olive oil to the pan. Once the oil gets very hot, start adding the croquettes to the pan without overcrowding, cook in batches. After about 1 minute turn the croquettes to cook the uncooked side and cook for another minute, then remove from the pan and transfer to a plate with a paper towel. Once all your croquettes are cooked transfer to a new plate. Enjoy!',
    }, {
        photo:'https://images.unsplash.com/photo-1651980927610-434846437c28?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGRldmlsZWQlMjBlZ2dzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=1600&q=60',
        label:'Huevos Rellenos de Atún',
        ingredients:['6 organic eggs', '1 clove of garlic (minced)',  '1/4 cup low-fat mayonnaise', '1 tsp dijon mustard', '1 tin Spanish tuna (oil drained', 'sea salt', 'freshly cracked black pepper', '1 roasted red bell pepper', 'dried Parsley' ],
        stepOne: 'Add 6 organic eggs into a sauce pan, fill the sauce pan with water (about 1 inch above the eggs), and heat the sauce pan with a HIGH heat, once the water comes to a rolling boil, place a lid on top and turn off the fire',
        stepTwo: '	After 10 minutes remove the lid from the sauce pan and transfer the eggs to a bowl with cold water for 5 minutes, then crack the eggs (I like to roll each egg on a flat surface for 20 seconds before I peel it, makes it a lot easier to peel), cut them in half and add the egg yolks into a bowl, set the egg whites aside',
        stepThree: 'Crumble the egg yolks in the bowl with a fork until well crumbled, then add a 1/4 cup of mayonnaise, 1 teaspoon of dijon mustard, 1 finely minced clove of garlic, 1 tin of high quality Spanish tuna (oil drained), season with sea salt and a generous portion of freshly cracked black pepper, and mix everything together until well mixed',
        stepFour: 'Evenly divide the egg yolk mixture into each egg white (I did it with a spoon), then cut a jarred roasted red bell pepper into thin strips and add 2 strips on top of each deviled egg, top them off with a little dried parsley',
        stepFive: 'Enjoy!',
    },
    {
        photo:'https://i0.wp.com/spainonafork.com/wp-content/uploads/2021/11/image11-7-11.png?fit=750%2C751&ssl=1',
        label:'Cheesy Garlic PULL-APART Bread',
        ingredients:['3 cups all-purpose flour', '3 tsp baking powder', '1 tsp sea salt', '1 1/2 tbsp dried oregano', '1/4 cup extra virgin olive oil', '1 cup water',  '7 oz block mild Manchego cheese', '4 cloves garlic' ],
        stepOne: 'Cut 24 cubes that are 1/2 inch by 1/2 inch from a block of Manchego cheese, then shred a generous 2 cups, set aside. Add 3 cups all-purpose flour into a large bowl, along with 3 tsp baking powder, 1 tsp sea salt and 1 tbsp dried oregano, mix the dry ingredients together, then add in 3 tbsp extra virgin olive oil and 1 cup water, mix all the ingredients together, once they start forming a dough get in there with your hands and continue to mix, once you end up with a compact dough, knead inside the bowl for 1 to 2 minutes, shape into a ball',
        stepTwo: 'Sprinkle some all-purpose flour on a clean flat surface, add the ball of dough on top, cut it into 3 evenly sized pieces, shape each one into a ball, cut each ball of dough into 8 evenly sized pieces, to end up with 24 pieces of dough. Grab a cube of the cheese and add into a piece of dough, seal the dough well over the cheese and shape into a ball, do this until you end up with 24 stuffed pieces of dough',
        stepThree: 'Line an 8-inch round baking pan with parchment paper, add the balls of dough, making sure they´re all tightly compacted together.',
        stepFour: 'Add a generous tbsp of extra virgin olive oil into a bowl, shred in 4 cloves of garlic and add in 1/2 tbsp dried oregano, mix until well combined, pour the mixture over the pieces of dough and brush all over until it´s evenly divided',
        stepFive: 'Add the baking pan into a preheated oven, bake + broil option 210 C - 425 F, after 15 minutes open the oven and slide the pan out, sprinkle the shredded cheese all over the bread and add back into the oven, after 5 minutes remove from the oven, transfer to a serving dish, sprinkle with freshly chopped parsley and serve at once, enjoy',
    },
    {
        photo:'https://images.unsplash.com/photo-1619926340139-9a2e2245a64e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80',
        label:'Crispy-Fried SPANISH EMPANADAS With VEGETABLE PISTO',
        ingredients:['2 tbsp extra virgin olive oil', '3 cloves garlic thinly sliced', '1/2 onion roughly chopped', '1/2 red bell pepper cut into 1/2 inch squares', '1/2 green bell pepper cut into 1/2 inch squares', '1/2 zucchini cut into 1/4 inch thick half moons', '15 ounce can diced tomatoes', 'sea salt', 'black pepper', 'white sugar', '2 cups all-purpose flour', '2 tsp baking powder', '1 tsp sea salt', '2 tbsp extra virgin olive oil', '2/3 cup water'],
        stepOne: 'To make the vegetable pisto, heat a sauce pan with a medium heat and add in 2 tablespoons of extra virgin olive oil, after 2 minutes add in 1/2 onion roughly chopped and 3 cloves garlic thinly sliced, mix with the olive oil, after 3 minutes add in 1/2 red & 1/2 green bell pepper cut into 1/2 inch squares and 1/2 zucchini cut into 1/4 inch thick half moons, continue to mix all the vegetables with the olive oil, after 5 minutes and all the vegetables are soft and tender, add in one 15 ounce can of diced tomatoes (drained) and season everything with sea salt, black pepper and a pinch of white sugar, mix together until well combined and lower the fire to a low-medium heat',
        stepTwo: 'To make the dough, add in 2 cups of all-purpose flour into a large bowl, 2 teaspoons of baking powder and 1 teaspoon of sea salt, mix the dry ingredients together, then add in 2 tablespoons of extra virgin olive oil and 2/3 cups water, mix together, once you start forming a dough get in there with your hands and continue to mix together, once well combined knead the dough inside the bowl for 1 to 2 minutes, then shape into a ball',
        stepThree: 'Sprinkle some all-purpose flour into a cleaned flat surface, add the ball of dough on top and cut into 8 evenly sized pieces',
        stepFour: 'To make each empanada, flatten out a piece of dough into a circular design that is 6 inches in diameter by 1/8 of an inch thick, then add in some of the vegetable pisto (about a 1/4 cup), fold the dough over the pisto to create a half moon design and seal the outer edges together with your fingers, then pierce the outer edges again with a fork on both sides to ensure they are well sealed, continue to do this until all the empanadas are done',
        stepFive: 'Heat a small fry pan with a medium heat and add in a generous 1/3 cup extra virgin olive oil, after 4 minutes add in one of the empanadas, cook in batches, after 60 to 75 seconds flip the empanada to cook the other side, after another 60 to 75 seconds remove from the pan and transfer to a dish with paper towels, continue to fry your empanadas in batches until done, serve hot or at room temperature, enjoy',
    },
    {
        photo:'https://i0.wp.com/spainonafork.wpengine.com/wp-content/uploads/2020/05/potatoes2-3-33.png?resize=531%2C800&ssl=1',
        label:'Garlic ROASTED POTATOES with MELTED CHEESE',
        ingredients:['3 yukon gold potatoes', '2 tbsp extra virgin olive oil', '5 cloves garlic', '2 cups shredded cheese', '1/2 tsp sweet smoked Spanish paprika', 'sea salt', 'freshly cracked black pepper', 'handful freshly chopped chives' ],
        stepOne: 'Rinse and pat dry 3 yukon gold potatoes, then cut each one into 1/2 inch thick pieces, I like to cut each potato in half, then each half in half to end up with 4 evenly sized quarters from each potato, cut each half right down the middle and into 1/2 inch pieces, add the cut potatoes into a large bowl',
        stepTwo: 'Shred in 5 large cloves of garlic over the potatoes (or you can finely mince them), pour in 2 tablespoons of extra virgin olive oil and season with sea salt & black pepper, toss together until well combined',
        stepThree: 'Transfer the coated potatoes into a baking tray lined with parchment paper, make sure they´re all in a single layer so they roast evenly, add into a preheated oven, bake + broil option 250 C - 475 F',
        stepFour: 'After 25 minutes remove the potatoes from the oven, transfer them into an oven-proof pan (or you can just leave them in the baking tray), sprinkle 2 cups of shredded cheese over the potatoes and a kiss of sweet smoked paprika, add back into the oven until the cheese is fully melted, remove from the oven and sprinkle with freshly chopped chives',
        stepFive: 'Enjoy!',
    },
    {
        photo:'https://149401384.v2.pressablecdn.com/wp-content/uploads/2007/01/really-simple-homemade-pizza-scaled.jpg',
        label:'No-Yeast No-Bake HOMEMADE PIZZA',
        ingredients:['1 cup all-purpose flour', '1 tsp baking powder', '1/2 tsp sea salt', '1 tbsp extra virgin olive oil', '1/3 cup water', '1 tbsp extra virgin olive oil', '1 clove garlic', '15 oz can tomato sauce', '15 oz can diced tomatoes', '1/2 tsp dried oregano', '1/2 tsp dried basil', 'sea salt', 'black pepper', 'white sugar', '1 1/2 cups shredded mozzarella', '2 jarred roasted red bell peppers', '10 black pitted olives', '1/2 tbsp extra virgin olive oil', 'handful fresh arugula'],
        stepOne: 'To make the tomato sauce, heat a sauce pan with a medium heat and add in a generous tablespoon of extra virgin olive oil, after 1 minute add in 1 clove garlic finely minced and mix with the oil, after 1 minute add in one 15 oz can tomato sauce, one 15 oz can diced tomatoes and season with 1/2 tsp dried oregano, 1/2 tsp dried basil, a pinch of sea salt, freshly cracked black pepper and a pinch of white sugar, mix together and lower the fire to a low heat',
        stepTwo: 'To make the pizza dough, add 1 cup of all-purpose flour into a large bowl, 1 tsp baking powder and 1/2 tsp sea salt, mix the dry ingredients together, then add in 1 tablespoon extra virgin olive oil and 1/3 cup water, mix together until you form a dough, then knead the dough inside of the bowl between one to two minutes, shape into a ball and set aside',
        stepThree: 'Sprinkle some all-purpose flour on a cleaned flat surface, place the ball of dough on top and shape into a circular design that is between a 1/4 inch to 1/8 inch in thickness',
        stepFour: 'Add 1/2 tablespoon extra virgin olive oil into a large frying pan, brush the olive oil to coat the entire surface, add the dough into the pan and mold it around so it fits in there like a glove, then using a fork, gently pierce the dough all over',
        stepFive: 'Add some of the tomato sauce over the dough and evenly spread around, sprinkle about 1 1/2 cups of shredded mozzarella and top off with strips of roasted red bell peppers and sliced black olives, place a lid on the pan and transfer to a stove top, heat with a low to low-medium heat, after 13 to 15 minutes, and the cheese is perfectly melted, remove the pan from the heat, transfer the pizza into a cutting board, sprinkle with freshly chopped arugula and serve at once, Enjoy!',
    },
    {
        photo:'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fmedium_2x%2Fpublic%2Fimage%2F2017%2F03%2Fmain%2Fshrimp-paella-1705p55.jpg%3Fitok%3DmwYjQm9l',
        label:'SPANISH PAELLA with Shrimp & Bell Peppers',
        ingredients:['1/4 cup extra virgin olive oil', '1/2 red bell pepper','1/2 green bell pepper', '1/2 onion', '4 cloves garlic','1 tsp sweet smoked Spanish paprika', '1/2 cup canned tomato sauce', '2 1/2 cups vegetable broth', '1/2 tsp saffron threads', '1 cup round rice', '12 raw jumbo shrimp peeled & deveined', 'sea salt', 'black pepper' ],
        stepOne: 'Finely mince 4 cloves of garlic, finely dice 1/2 of an onion, roughly dice 1/2 red & 1/2 green bell pepper, pat down 12 raw jumbo shrimp (peeled & deveined) with some paper towels and season with sea salt & black pepper',
        stepTwo: 'Heat a paella pan with a medium-high heat and add in 1/4 cup extra virgin olive oil, after 1 minute add in the diced bell peppers and mix around with the olive oil, after 2 minutes add in the diced onions and continue to mix, 2 minutes later add in the minced garlic and continue to mix, 30 seconds later add in 1 teaspoon of sweet smoked paprika and mix it all together until well combined, then add in 1/2 cup canned tomato sauce and season everything with sea salt & black pepper, once again mix all together until well combined',
        stepThree: 'One minute after adding the tomato sauce, add in 2 1/2 cups of vegetable broth, pinch in 1/2 teaspoon saffron threads and give it a quick mix, once it comes to a boil, let it boil for an extra minute so the saffron can infuse into the broth, then add in 1 cup of round rice, give it a quick mix so everything is evenly distributed, after this step do not mix the rice again, otherwise it will distrup the way the rice cooks, 6 minutes after adding the rice add in the shrimp into the pan, 2 minutes later lower the fire to a low-medium heat and simmer',
        stepFour: 'After simmering for 5 minutes and there is virtually no broth left, hit it back to a medium-high heat and go for 60 to 90 seconds, this will create the socarrat (caramelized burnt rice underneath), then remove the pan from the heat and cover with a dishcloth, after 5 minutes uncover the paella and serve at once',
        stepFive: 'Enjoy!',
    }
    // {
    //     photo:'',
    //     label:'',
    //     ingredients:[],
    //     stepOne: '',
    //     stepTwo: '',
    //     stepThree: '',
    //     stepFour: '',
    //     stepFive: '',
    // },
    // {
    //     photo:'',
    //     label:'',
    //     ingredients:[],
    //     stepOne: '',
    //     stepTwo: '',
    //     stepThree: '',
    //     stepFour: '',
    //     stepFive: '',
    // },

]

exports.veggies = [
    {
        photo: 'https://cdn.loveandlemons.com/wp-content/uploads/2018/09/vegan-pizza.jpg',
        label:'Vegan Pizza',
        ingredients:['1 small head broccoli, florets chopped into small pieces, top of stalk diced (1/2 cup)', '1/3 cup halved cherry tomatoes', 'kernels from 1 ear fresh corn', '1/4 cup coarsely chopped red onion', '1/2 jalapeño, thinly sliced', '4 oil-packed sun-dried tomatoes, diced',  'extra-virgin olive oil, for drizzling and brushing', '1 (16-ounce) ball of pizza dough', '1/2 cup fresh basil leaves', '2 tablespoons fresh thyme leaves', 'pinches of red pepper flakes', 'sea salt and freshly ground black pepper', 'ceshew cream'],
        stepOne: 'Preheat the oven to 450°F.',
        stepTwo: 'In a medium bowl, combine the broccoli, tomatoes, corn, onion, jalapeño, and sun-dried tomatoes and drizzle with olive oil and pinches of salt and pepper. Toss to coat and taste. The vegetables should be well-seasoned and well-coated with the olive oil so that the vegetables are flavorful throughout the pizza.',
        stepThree: 'Stretch the pizza dough onto a 14-inch pizza pan. Brush the outer edges of the dough lightly with olive oil and spoon a few scoops of cashew cream onto the center of the dough, just enough to spread it into a thin layer. Distribute the vegetables onto the dough.',
        stepFour: 'Bake 15 minutes, or until the crust is golden, cooked through, and the broccoli is tender and roasted. Remove from the oven and drizzle generously with the cashew cream (if your cashew cream is too thick to drizzle, stir in a little water). Top with the fresh basil, fresh thyme, and pinches of red pepper flakes.',
        stepFive: 'Enjoy',
    },
]

exports.cocktails = [
    {
        photo:'https://www.eatthis.com/wp-content/uploads/sites/4/2020/08/horse-neck.jpg?quality=82&strip=all',
        label:"The Horse's Neck",
        ingredients:['2 oz High West Double Rye', '0.25 oz fresh ginger juice', '0.25 oz fresh-squeezed lemon juice', '2 oz light ginger beer', 'Lemon twist garnish'],
        recipe: 'Fill an Old Fashioned glass with chip ice. Then pour ingredients into the glass and garnish with a lemon twist.'
    }
]